# Generated by Django 5.2.5 on 2025-08-17 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dlc', models.CharField(max_length=5)),
                ('ingredient_image_url', models.URLField(blank=True, max_length=100)),
                ('spoil_time', models.IntegerField()),
                ('food_quality', models.JSONField()),
                ('kcal_per_kg', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('source_image_url', models.URLField(blank=True, max_length=100)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_required', models.IntegerField()),
                ('unit', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[('main', 'Main'), ('alternate', 'Alternate')], max_length=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeONI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Placeholder', max_length=50, unique=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image_url', models.URLField(blank=True, max_length=100)),
                ('dlc', models.CharField(max_length=5)),
                ('food_quality', models.JSONField()),
                ('spoil_time', models.IntegerField()),
                ('kcal_per_kg', models.IntegerField()),
                ('source', models.CharField(max_length=50)),
                ('source_image_url', models.URLField(blank=True, max_length=100)),
                ('calories_produced', models.IntegerField()),
                ('slug', models.SlugField(null=True)),
                ('ingredients', models.ManyToManyField(related_name='recipes', through='v2.RecipeIngredients', to='v2.ingredients')),
            ],
        ),
        migrations.AddField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v2.recipeoni'),
        ),
    ]
