# Generated by Django 5.2.5 on 2025-08-18 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name': 'Recipe Ingredients', 'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipeoni',
            options={'verbose_name': 'ONI Recipe', 'verbose_name_plural': 'ONI Recipes'},
        ),
    ]
