# Generated by Django 5.2.5 on 2025-09-05 07:40

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
        migrations.AlterField(
            model_name='recipeoni',
            name='food_quality',
            field=models.JSONField(default='{"Quality": "standard", "Morale impact": "+0"}'),
        ),
        migrations.AlterField(
            model_name='recipeoni',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='name', unique=True),
        ),
    ]
