# Generated by Django 5.2.5 on 2025-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0002_alter_ingredients_slug_alter_recipeoni_food_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='food_quality',
            field=models.JSONField(default='Food quality & Morale Impact'),
        ),
        migrations.AlterField(
            model_name='recipeoni',
            name='food_quality',
            field=models.JSONField(default='Food quality & Morale Impact'),
        ),
    ]
