# Generated by Django 5.2.5 on 2025-09-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0003_alter_ingredients_food_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='food_quality',
            field=models.JSONField(help_text='{Food quality: Standard, Morale impact: +2}'),
        ),
        migrations.AlterField(
            model_name='recipeoni',
            name='food_quality',
            field=models.JSONField(help_text='{Food quality: Standard, Morale impact: +2}'),
        ),
    ]
