# Generated by Django 5.2.5 on 2025-09-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0004_alter_ingredients_food_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeoni',
            name='food_quality',
            field=models.JSONField(help_text='{"Food quality": "Standard", "Morale impact": +2}'),
        ),
    ]
