# Generated by Django 5.2.5 on 2025-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0005_alter_recipeoni_food_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='food_quality',
            field=models.JSONField(help_text='{"Quality": "standard", "Morale impact": "+0"}'),
        ),
        migrations.AlterField(
            model_name='recipeoni',
            name='food_quality',
            field=models.JSONField(help_text='{"Quality": "standard", "Morale impact": "+0"}'),
        ),
    ]
