# Generated by Django 5.2.5 on 2025-09-07 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0007_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='v3.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='v3.recipeoni')),
            ],
        ),
    ]
