# Generated by Django 5.2.5 on 2025-09-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0009_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
