# Generated by Django 5.2.5 on 2025-09-08 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0010_ingredients_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderer_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FoodManagermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(default='Food', max_length=30)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v3.recipeoni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='v3.orders')),
            ],
            options={
                'verbose_name': 'Food order item',
                'verbose_name_plural': 'Food order items',
            },
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
