# Generated by Django 5.2.5 on 2025-09-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0012_alter_orders_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodManagermodel',
            new_name='FoodOrdersModel',
        ),
    ]
