# Generated by Django 5.2.5 on 2025-09-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0013_rename_foodmanagermodel_foodordersmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodOrdersModel',
            new_name='FoodOrders',
        ),
    ]
