# Generated by Django 5.2.5 on 2025-09-12 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0014_rename_foodordersmodel_foodorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodorders',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='foodorders',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_order_item', to='v3.recipeoni'),
        ),
        migrations.AlterField(
            model_name='foodorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v3.orders'),
        ),
    ]
