# Generated by Django 5.2.5 on 2025-09-12 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0015_alter_foodorders_category_alter_foodorders_food_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ONIBuildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ONIElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v3.orders')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_order_item', to='v3.onibuildings')),
            ],
            options={
                'verbose_name': 'Building order item',
                'verbose_name_plural': 'Building order items',
            },
        ),
        migrations.CreateModel(
            name='ElementOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v3.orders')),
                ('element_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_order_item', to='v3.onielements')),
            ],
            options={
                'verbose_name': 'Element order item',
                'verbose_name_plural': 'Element order items',
            },
        ),
    ]
