# Generated by Django 5.2.5 on 2025-09-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0016_onibuildings_onielements_buildingorders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buildingorders',
            name='order',
        ),
        migrations.RemoveField(
            model_name='elementorders',
            name='order',
        ),
        migrations.AddField(
            model_name='onielements',
            name='description',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onielements',
            name='dlc',
            field=models.CharField(default='base', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='onielements',
            name='name',
            field=models.CharField(default='placeholder', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodorders',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to='v3.orders'),
        ),
    ]
