# Generated by Django 5.2.5 on 2025-09-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0017_remove_buildingorders_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementorders',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='element_orders', to='v3.orders'),
            preserve_default=False,
        ),
    ]
