# Generated by Django 5.2.5 on 2025-10-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v3', '0018_elementorders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', help_text='Pending, Completed or Canceled', max_length=20),
        ),
    ]
